import { PERMS_ACCESS_HOME_PAGE } from './common';

export const PERMS_ADMIN_LOGIN = 'PERMS_ADMIN_LOGIN';

export const PERMS_ADMIN_LOGOUT = 'PERMS_ADMIN_LOGOUT';

export const PERMS_ADMIN_UPDATE = 'PERMS_ADMIN_UPDATE';

export const PERMS_ADD_USER_PERMISSION = 'PERMS_ADD_USER_PERMISSION';

export const ADMIN_DEFAULT_PERMISSIONS = {
  PERMS_ADMIN_LOGIN,
  PERMS_ADMIN_LOGOUT,
  PERMS_ACCESS_HOME_PAGE,
};
