import { PERMS_ACCESS_HOME_PAGE } from './common';

export const PERMS_USER_LOGIN = 'PERMS_USER_LOGIN';

export const PERMS_USER_LOGOUT = 'PERMS_USER_LOGOUT';

export const USER_DEFAULTS_PERMISSIONS = {
  PERMS_USER_LOGOUT,
  PERMS_USER_LOGIN,
  PERMS_ACCESS_HOME_PAGE,
};
