export const USER_CREATED = 'USER_CREATED';

export const ADMIN_CREATED = 'ADMIN_CREATED';

export const USER_CREATED_SESSION_REGISTERED =
  'USER_CREATED_SESSION_REGISTERED';

export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ADMIN_LOGIN = 'ADMIN_LOGIN';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_CREATED_SESSION_REGISTERED =
  'ADMIN_CREATED_SESSION_REGISTERED';

export const USER_PERMISSION_CHANGE = 'USER_PERMISSION_CHANGE';
